set(ORBSVCS_CMAKE_LIST_DIR ${CMAKE_CURRENT_LIST_DIR})

list(APPEND TAO_BASE_IDL_FLAGS
  -Sa -St
  -Wb,versioning_begin=TAO_BEGIN_VERSIONED_NAMESPACE_DECL
  -Wb,versioning_end=TAO_END_VERSIONED_NAMESPACE_DECL
  -I$(ORBSVCS_CMAKE_LIST_DIR)/..
)

