option(CORBA_E_MICRO "" OFF)
option(CORBA_E_COMPACT "" OFF)
option(MINIMUM_CORBA "" OFF)
option(TAO_NO_IIOP "" OFF)
option(OPTIMIZE_COLLOCATED_INVOCATIONS "" ON)
option(VALUETYPE_OUT_INDIRECTION "" ON)
option(CORBA_MESSAGING "" ON)
option(AMI "" ON)
option(CORBA_MESSAGING "" ON)
option(TRANSPORT_CURRENT "" ON)
option(NEGOTIATE_CODESETS "" OFF)
# option(LINK_CODECFACTORY "" OFF)
option(INTERCEPTORS "" ON)
option(RT_CORBA "" ON)


if (MINIMUM_CORBA OR CORBA_E_MICRO OR CORBA_E_COMPACT)
  set(INTERCEPTORS CACHE INTERNAL "" FORCE)
endif()



if (RT_CORBA AND NOT CORBA_MESSAGING)
  message(FATAL_ERROR "RT_CORBA requires CORBA_MESSAGING to be enabled")
endif()

if (AMI AND NOT CORBA_MESSAGING)
  message(FATAL_ERROR "AMI requires CORBA_MESSAGING to be enabled")
endif()

set(TAO_OPTIONS
  CORBA_E_MICRO
  CORBA_E_COMPACT
  MINIMUM_CORBA
  TAO_NO_IIOP
  OPTIMIZE_COLLOCATED_INVOCATIONS
  RT_CORBA
  # GEN_OSTREAM   ### come from ace_options.cmake
  INTERCEPTORS
  CORBA_MESSAGING
  TRANSPORT_CURRENT
)