## NEGOTIATE_CODESETS ASPECT
if (NEGOTIATE_CODESETS)
  set(NEGOTIATE_CODESETS_COMPILE_DEFINITIONS TAO_EXPLICIT_NEGOTIATE_CODESETS)
  set(NEGOTIATE_CODESETS_LINK_LIBRARIES TAO_Codeset)
endif()


## MESSAGING_OPTIONAL ASPECT
if (CORBA_MESSAGING)
	set(MESSAGING_OPTIONAL_LINK_LIBRARIES TAO_Messaging)
else()
  set(MESSAGING_OPTIONAL_COMPILE_DEFINITIONS TAO_HAS_CORBA_MESSAGING=0)
endif()


## TAO ASPECT
if (LINK_CODEFACTORY)
  set(TAO_LINK_LIBRARIES TAO_CodeFactory)
else()
  set(TAO_LINK_LIBRARIES TAO)
endif()

## TAOCLIENT ASPECT
set(TAOCLIENT_COMPILE_DEFINITIONS ${NEGOTIATE_CODESETS_COMPILE_DEFINITIONS})
set(TAOCLIENT_LINK_LIBRARIES ${TAO_LINK_LIBRARIES} ${NEGOTIATE_CODESETS_LINK_LIBRARIES})

## TAOSERVER ASPECT
set(TAOSERVER_COMPILE_DEFINITIONS ${NEGOTIATE_CODESETS_COMPILE_DEFINITIONS})
set(TAOSERVER_LINK_LIBRARIES ${TAO_LINK_LIBRARIES} TAO_PortableServer ${NEGOTIATE_CODESETS_LINK_LIBRARIES})


## RT_CLIENT ASPECT
set(RT_CLIENT_COMPILE_DEFINITIONS ${NEGOTIATE_CODESETS_COMPILE_DEFINITIONS})
set(RT_CLIENT_LINK_LIBRARIES ${TAO_CLIENT_LINK_LIBRARIES} TAO_RT_CORBA)

## RT_SERVER ASPECT
set(RT_SERVER_COMPILE_DEFINITIONS ${NEGOTIATE_CODESETS_COMPILE_DEFINITIONS})
set(RT_SERVER_LINK_LIBRARIES ${TAO_SERVER_LINK_LIBRARIES} TAO_RTPortableServer)

## AMI ASPECT
set(AMI_TAO_IDL_FLAGS -GC)
set(AMI_LINK_LIBRARIES TAO_Messaging)


## AMH ASPECT
set(AMH_TAO_IDL_FLAGS -GH)
set(AMH_LINK_LIBRARIES TAO_Messaging)